[package]
name = "ssv_jen"
version = "0.1.0"
authors = ["Aden Kenny <adenkenny@gmail.com>"]
edition = "2018"


[profile.release]
opt-level = 3


[dependencies]

structopt = "0.3.13"
jen = { version = "1.0.1", default-features = false }
chrono = "0.4"
serde_json = "1.0.59"
clap = "2.27.0"
